from scipy.fft import fft, ifft  # Update to use scipy.fft instead of numpy.fft

def GUM_DFT(x, ux, N=None):
    # ... existing code ...
    X = fft(x, n=N)  # Use scipy.fft.fft instead of numpy.fft.fft
    # ... existing code ...

def GUM_iDFT(X, UX, Nx=None):
    # ... existing code ...
    x = ifft(X, n=Nx)  # Use scipy.fft.ifft instead of numpy.fft.ifft
    # ... existing code ...
